# Generated by Django 4.2.10 on 2024-04-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionParcelles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GestionParcelles',
            new_name='Parcelles',
        ),
    ]
